name: gm-dev
services:
  # [gm-storage]
  db:
    container_name: "gm-dev-db"
    image: postgres:14.12-bullseye
    # [Source](https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/)
    ports:
      - "5432:5432"
    environment:
      # [Environment Variables for Postgres Img](https://hub.docker.com/_/postgres)
      - POSTGRES_DB=gm
      - POSTGRES_PASSWORD=admin
    volumes:
      # This is where the DDL would go, for now it just is a placeholder.
      - "../gm-storage/core/src/main/sql/:/docker-entrypoint-initdb.d/"
      # Persist data between sessions.
      - data:/var/lib/postgresql/data
volumes:
  data:
