# -----------------------------------------
# Application Configuration
# -----------------------------------------
spring.application.name=Curator
app.client.url=http://localhost:4200
# -----------------------------------------
# Spring Config
# -----------------------------------------
spring.task.scheduling.thread-name-prefix=Chronos-
# -----------------------------------------
# Logging Levels
# -----------------------------------------
logging.level.root=WARN
logging.level.com.bobo.storage=INFO
# -----------------------------------------
# 'Handle' Warnings
# -----------------------------------------
# I don't really understand this, but from what I can glean this property is set to true by default
# and causes a transaction to be made and kept open for each controller mapping.
# The transaction would only end when a response is returned.
# I believe it is defaulted to true for use with the embedded tomcat server,
# which I am using during dev. During deployment, it should be set to false.
spring.jpa.open-in-view=false