<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.bobo</groupId>
    <artifactId>song-storage</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>core</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.bobo</groupId>
      <artifactId>semantic</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!--        Persistence-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <!--        Driver-->
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
    <!--        /Persistence-->

    <!--        Lookup Polling -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <!--        Lookup Polling -->

    <!--        Testing-->
    <dependency>
      <groupId>com.bobo</groupId>
      <artifactId>semantic</artifactId>
      <version>${project.version}</version>
      <classifier>tests</classifier>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
    </dependency>

    <dependency>
      <!--            In Memory DB-->
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
    <!--            /Testing-->
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <!--                Export Core Test Utils-->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.4.2</version>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <excludes>
                <!--                                TODO [housekeeping] Figure out how to configure a step to compile and package the test-->
                <!--                                jars during the regular package goal. I want to compile, but exclude the tests classes,-->
                <!--                                so I only export my Test Utilities in the test-jar.-->
                <!--                                -->
                <!--                                This is a workaround. It fires after all my tests have been compiled and executed,-->
                <!--                                and if I do Dmaven.test.skip=true it will skip the creation of my test-jar.-->
                <!--                                -->
                <!--                                I may be misunderstanding the idea of the test-jar goal.-->
                <exclude>**/*Test.class</exclude>
                <exclude>**/*IT.class</exclude>
              </excludes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
