create table song(
-- Primary
id integer generated by default as identity primary key,
url varchar(2048) not null unique, -- no standard for URL max length. Best approx. ~2,000 chars.
-- Song Information
title varchar(256),
artist varchar(256),
thumbnail_url varchar(2048)
);

create type job_status as ENUM (
-- https://www.postgresql.org/docs/current/datatype-enum.html
'PENDING',
'PROCESSING',
'DONE',
'INVALID'
);

create table song_lookup(
-- Primary
song_id integer not null primary key references song(id) on delete cascade,
status job_status not null default 'PENDING', -- potential target for indexing later on.
-- Metadata
	last_lookup timestamp with time zone,
last_modified timestamp with time zone not null default now(),
failed smallint not null default 0
);

create table playlist(
-- Primary
id integer generated by default as identity primary key,
name varchar(255) not null -- potential target for indexing later on.
);

create table playlist_song(
-- Primary
id integer generated by default as identity primary key,
playlist_id integer not null,
foreign key (playlist_id) references playlist(id),
song_id integer not null,
foreign key (song_id) references song(id)
--unique(playlist_id, song_id) -- for now, the same Song can occur multiple times in a Playlist.
-- Playlist Song Information
--position smallint -- but we have not yet gotten to this stage as yet.
);

create table tag(
-- Primary
id integer generated by default as identity primary key,
tag varchar(255) not null,
constraint uq_tag unique(tag)
);

create table song_tag(
-- Primary
id integer generated by default as identity primary key,
song_id integer not null,
foreign key (song_id) references song(id),
tag_id integer not null,
foreign key (tag_id) references tag(id),
constraint uq_song_tag unique(song_id,tag_id)
);